version: 2.1
orbs:
    firebase-deploy: azdevs/firebase-deploy@1.0.0
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:chakracore-8.11-browsers-legacy
        steps:
            - checkout
            - run:
                name: Install n
                command: sudo npm install -g n
            - run:
                name: Set stable node version
                command: sudo n stable
            - run:
                name: Show node version
                command: node -v
            - run:
                name: Show npm version
                command: npm -v
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: Show current directory
                command: pwd
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Linting
                command: npm run lint
            - run:
                name: Building
                command: npm run build-prod
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - package.json
                    - firebase.json
                    - .firebaserc

    deploy:
        description: Deploy to Firebase
        docker:
            - image: 'circleci/node:lts'
        steps:
            - run:
                    name: Install Firebase Tools
                    command: npm install firebase-tools
            - run:
                    name: Deploy to Firebase
                    command: npm run deploy

workflows:
    version: 2
    -deploy:
        jobs:
        - build
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
